[package]
name = "rover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
base64 = "0.13.0"
bech32 = "0.8.1"
bip32 = { version = "0.3.0", features = ["secp256k1", "bip39"] }
chrono = "0.4.19"
cosmos-sdk-proto = { git = "https://github.com/rnbguy/cosmos-rust" }
der-parser = "7.0.0"
futures = "0.3.21"
gql_client = "1.0.4"
keyring = "1.1.2"
lazy_static = "1.4.0"
ledger-apdu = "0.8.0"
ledger-transport = "0.8.0"
ledger-transport-hid = "0.8.0"
prost = "0.9.0"
prost-wkt-types = "0.3.0"
ripemd = "0.1.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
serde_yaml = "0.8.23"
sha2 = "0.10.2"
tendermint = "0.23.5"
tendermint-rpc = { version = "0.23.5", features = ["http-client"] }
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["rt-multi-thread"] }
tracing = "0.1.32"
ureq = { version = "2.4.0", features = ["json"] }
url = "2.2.2"
